### PR TITLE
resolve #168: adjust with default y

### LINKED ISSUE #168: Keyboard Layout Broken
When connecting Crkbd, the rendered keyboard layout is broken like the following:

crkbd

### PR DESCRIPTION
**Pull request by adamrocker**

### CODE REVIEW

**Comment by adamrocker** [comment]
スクリーンショット 2021-01-16 18 26 01

I've tested some keyboards works fine.

@yoichiro Could you please test this code with your Lunakey Mini?

**Comment by yoichiro** [comment]
@adamrocker Sure!

**Comment by yoichiro** [comment]
When testing for Lunakey Mini, I got the following result:

スクリーンショット 2021-01-16 18 53 50

There is no problem.

**Review by yoichiro — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
